<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <!--includes-->
    <xacro:include filename="inertial_macros.xacro"/>
    <xacro:include filename="materials.xacro"/>

  <!-- Variables -->
    <xacro:property name="M_PI" value="3.14159"/>

  <!-- Vehicle Geometries -->
    <xacro:property name="base_x_size" value="0.6200000" />
    <xacro:property name="base_y_size" value="0.585000" />
    <xacro:property name="base_z_size" value="0.235000" />

    <xacro:property name="wheelbase" value="0.463951"/>
    <xacro:property name="track" value="0.416503"/>
    <xacro:property name="wheel_vertical_offset" value="-0.100998" />

    <xacro:property name="wheel_length" value="0.8e-01" />
    <xacro:property name="wheel_radius" value="1.600e-01" />
	
    <!-- BASE LINK -->
    <link name="base_link">

    </link>


     <!-- BASE FOOTPRINT LINK -->
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 -0.05" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    
    </link>


    <!-- CHASSIS LINK -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 0"/>
    </joint>

    <link name="chassis">
      <visual>
        <origin xyz="0 0 0" rpy="1.5707 0 -1.5707" />
        <geometry>
          <mesh filename="file://$(find scout)/urdf/meshes/scout_mini_base_link.dae" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.5707 0 -1.5707" />
        <geometry>
          <mesh filename="file://$(find scout)/urdf/meshes/scout_mini_base_link_collision.stl" />
        </geometry>
      </collision>
        <xacro:inertial_box mass="0.5" x="0.3" y="0.3" z="0.15">
            <origin xyz="0.15 0 0.075" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Purple</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
      <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
      <axis xyz="0 1 0" rpy="0 0 0" />
    </joint>

    <link name="left_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="-${M_PI/2} 0 0" />
        <geometry>
          <mesh filename="file://$(find scout)/urdf/meshes/wheel.dae" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="-${M_PI/2} 0 0" />
        <geometry>
          <mesh filename="file://$(find scout)/urdf/meshes/wheel_collision.stl" />
        </geometry>
      </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>


    <!-- RIGHT WHEEL LINK -->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
      <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
      <axis xyz="0 1 0" rpy="0 0 0" />
    </joint>

    <link name="right_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry>
          <mesh filename="file://$(find scout)/urdf/meshes/wheel.dae" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry>
          <mesh filename="file://$(find scout)/urdf/meshes/wheel_collision.stl" />
        </geometry>
      </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>





    <!-- LEFT WHEEL front LINK -->
    <joint name="left_wheel_front_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_front"/>
      <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
      <axis xyz="0 1 0" rpy="0 0 0" />
    </joint>

    <link name="left_wheel_front">
      <visual>
        <origin xyz="0 0 0" rpy="-${M_PI/2} 0 0" />
        <geometry>
          <mesh filename="file://$(find scout)/urdf/meshes/wheel.dae" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="-${M_PI/2} 0 0" />
        <geometry>
          <mesh filename="file://$(find scout)/urdf/meshes/wheel_collision.stl" />
        </geometry>
      </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel_front">
        <material>Gazebo/Black</material>
    </gazebo>


    <!-- RIGHT WHEEL front LINK -->
    <joint name="right_wheel_front_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_front"/>
      <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
      <axis xyz="0 1 0" rpy="0 0 0" />
    </joint>

    <link name="right_wheel_front">
      <visual>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry>
          <mesh filename="file://$(find scout)/urdf/meshes/wheel.dae" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry>
          <mesh filename="file://$(find scout)/urdf/meshes/wheel_collision.stl" />
        </geometry>
      </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel_front">
        <material>Gazebo/Black</material>
    </gazebo>
    
</robot>